### ISSUE TITLE
SkipChildren option not working in validator

### ISSUE THREAD

**Issue by ankithans** [aerogear/charmil#151] opened 2021-07-07 17:34 UTC
SkipChildren only works for root command, not for command path. 
For eg. root command for rhoas-cli is `rhoas`. It works for this, but not for `rhoas kafka` (contains ..list, ..create etc)

**Comment by wtrocki** [comment] 2021-07-07 18:05
We need some basic unit tests to see this type of issues before we release.

**Comment by ankithans** [comment] 2021-07-07 18:10
actually right, this happened for more than 2 times, I can do this 👍

**Comment by wtrocki** [comment] 2021-07-08 09:34
This is also duplicate of removing examples. We rely on examples to test things. My take is that unit tests can have some very bare commands structures etc. thus giving better testing capabilities.

**Closed** 2021-07-15 15:24 UTC
Labels: bug
